site_name: Cope and Drag Docs
repo_url: https://github.com/sidprasad/copeanddrag
site_url: https://sidprasad.github.io/copeanddrag/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started: getting-started/index.md
  - FAQ: faq.md
  - Examples: examples/index.md
  - Constraints: constraints.md
  - Directives: directives.md

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.highlight

